# Generated by Django 4.0.2 on 2022-03-21 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostpet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lost_pet_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
